[helpers]

[default]
depends = []

[default.files]
fishuser = "~/.config/fish/user.fish"
fontconfig = "~/.config/fontconfig/"
vscode = "~/.config/code-flags.conf"
hypruser = "~/.config/hypr/userprefs.conf"
[default.variables]

[settings]
default_target_type = "automatic"
